name: Update personal readme
on: 
    push:
        branches: [ master ]
    schedule:
        - cron: '0 6 * * *'
    workflow_dispatch:

jobs: 
    update-readme:
        name: update latest post and github summary
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Generate Github contribution grid snake
              uses: Platane/snk@master
              with:
                github_user_name: ${{ github.repository_owner }}
                svg_out_path: profile-summary-card-output/github-contribution-grid-snake.svg

            - name: Get last commit message
              id: last-commit-message
              run: |
                echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: ${{ steps.last-commit-message.outputs.msg }}
                commit_options: '--amend --no-edit --allow-empty'
                push_options: '--force'
                skip_fetch: true
                # Optional commit user and author settings
                commit_user_name: profile-summary-cards[bot]
                commit_user_email: profile-summary-cards-bot@example.com
                commit_author: profile-summary-cards[bot] <profile-summary-cards-bot@example.com>

